<?php 
require_once('./Message/WXAbstractMessage.php');
require_once('./Message/WXAbstractPassiveMessage.php');
require_once('./Message/WXTextPassiveMessage.php');
require_once('./Message/WXImagePassiveMessage.php');
require_once('./Message/WXVoicePassiveMessage.php');
require_once('./Message/WXVideoPassiveMessage.php');
require_once('./Message/WXMusicPassiveMessage.php');
require_once('./Message/WXMessageManager.php');
?>